### ISSUE TITLE
Create An Automated Webdriver IO Test Creator Based on Test Examples

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-dev-site#118]
# Feature Request

## Description

Storybook has a concept called [storyshots](https://github.com/storybooks/storybook/tree/master/addons/storyshots/storyshots-core/src) which allow you to write code like the following in order to Jest test all storybook examples:

```javascript
import initStoryshots from '@storybook/addon-storyshots';

initStoryshots();
```
We are already encouraging developers to create hidden "test" routes that will be used for wdio tests.  We should in theory be able to use the dev site configuration to discover routes that need testing and execute them automatically.  At a base level, this could include simple non-interactive tests.  It could in theory allow for more complex tests with a little consumer-defined configuration.

## Advantages

Advantages of this include:

* Less testing code written by consumers
* Greater control over screenshots and view port size logic
* Testing code living alongside the example

## Design

**Modification to Site Config**

Create a new option (wdioPageTypes) to flag certain pageTypes as ones that should have wdio tests generated for them automatically

**Metadata for Test Examples**

In order to support more complex tests, each test example can define its own metadata that supports:

* viewports - The viewports associated to this example
* selector - The selector to use when taking screenshots
* themeableProperties - Any themeable properties that should also be tested
* accessibilityRules - Any accessibility rules that should be considered when testing
* steps - An array of objects containing the following
  * action - A function that should be run as part of this step
  * name - An optional name to use to distinguish this test
  * selector - Takes precedence over the test level one
  * accessibilityRules - Takes precedence over the test level one
  * themeableProperties - Takes precedence over the test level one

**wdioTestDevSiteSnapshots**

Create a new function that will be used to generate tests automatically.  It will take the following options:

* package - For use in monorepos so that tests can be created for a single package within the monorepo

This function will parse the dev site config and for each page type in wdioPageTypes, determine the following:

* name - The name of the page
* groupingDirectory - The directory in which to place the screenshots, this will map to the directory structure of dev site.  It will be passed to a new parameter in `Terra.should.matchScreenshot` added in [this issue](https://github.com/cerner/terra-toolkit/issues/191).
* selector - The selector to use when taking screenshots
* url - The url to hit for this page
* themeableProperties - Any themeable properties that should also be tested
* accessibilityRules - Any accessibility rules that should be considered when testing
* steps - An array of steps to include as part of testing.  Each step may have its own set of selectors, themeableProperties, and accessibilityRules that will take precedence over the test level counterpart

Then, a test will be created that navigates to the url, executes the appropriate steps, screenshots, tests accessibility.  It will then take corresponding screenshots with the appropriate themeable properties when necessary.

The above will be aggregated for each viewport corresponding to each example and will run all examples for a given viewport before proceeding to the next one.

## Additional Context / Screenshots

I've prototyped this out.  Here are some concrete examples

* [New Configuration](https://github.com/cerner/terra-dev-site/blob/dev-site-spec/config/site/site.config.js#L72-L73)
* Metadata
  * [Example 1](https://github.com/cerner/terra-clinical/blob/dev-site-spec/packages/terra-clinical-data-grid/src/terra-dev-site/test/clinical-data-grid/CustomHeightDataGrid.metadata.js)
  * [Example 2](https://github.com/cerner/terra-clinical/blob/dev-site-spec/packages/terra-clinical-data-grid/src/terra-dev-site/test/clinical-data-grid/NoOverflowColumnDataGrid.metadata.js)
* Usage of wdioTestDevSiteSnapshots
  * [No Metadata Needed](https://github.com/cerner/terra-clinical/blob/dev-site-spec/packages/terra-clinical-application/tests/wdio/dev-site-spec.js)
  * [Metadata Needed](https://github.com/cerner/terra-clinical/blob/dev-site-spec/packages/terra-clinical-data-grid/tests/wdio/dev-site-spec.js)

**Comment by emilyrohrbough** [comment]
I think this auto-generated setup is pretty neat! I have some reservations on the details - in a way I think we might be trying to do too much and I think this approach may be confusing to explain to consumers. t think it would be easier do less, at least initially and add more functionality as we see more use cases. 

Here are some thoughts that I have:

#### Remove the metadata configuration files. A few reasons:
1. This moves test information way from tests/wdio/* pattern we've been pushing and it makes it 'hidden' to new developers.
2. This will add additional bulk to the released components that is not clearly distinguished as test specific.
3. We can easily pass this configuration at the test (*-spec) level.

#### Test-Specific Metadata Options:
Of the meta data options, I feel like these should be test (*-spec) specific:
- viewports: +1 with fallback to wdio formFactor value
- selector: +1 with fallback to wdio global selector

#### Example-Specific Metadata Options
Then, instead of metadata we could allow a json of example specific configurations that uses the example name as the key value:
- `selector`: +1 with fallback to test specific selector
- `viewports`: +1 with fallback to test specific viewports
- `accessibilityRules`: +1 but as `axeOptions` to match Axe Service terminology
- `themeableProperties`: +1 be passed
- `actions`: I say lets drop this: IMO passing actions is too tricky and 'hidden' from the consumer. Do we execute these between both wdio and a11y tests? Do we take before and after action screenshots? That might be too much? I feel these should be left for consumers to write for themselves so we don't assume to much and they understand the test flow. 

#### Dropping Metadata and Defining as Test Setup
Instead of metadata, we would have a testSetup which we pass to the `wdioTestDevSiteSnapshots` helper:
```
const testSetup: {
    viewports: ['medium', 'huge'],
    selector: '#root',
    examples: {  
        'defaultComponent': {
            selector: '#no-overflow-column-data-grid'
            axeOptions: { ... } 
            themeableProperties: { ... },
        }
    }
};
```

#### Example Usage
Then using data-grid metadata examples you provided, the component's test spec would look like:

```diff
// eslint-disable-next-line import/no-extraneous-dependencies
const wdioTestDevSiteSnapshots = require('terra-dev-site/lib/dev-site-snapshots/wdio/wdioTestDevSiteSnapshots').default;

const testSetup: {
    viewports: ['medium', 'huge'],
    examples: {  
        'CustomHeightDataGrid': {
            selector: '#custom-height-data-grid',
            themeableProperties: { ... }
        }
        'NoOverflowColumnDataGrid': {
            selector: '#no-overflow-column-data-grid'
            themeableProperties: { ... },
        }
    }
};

// auto-generated test specs
wdioTestDevSiteSnapshots({
  package: 'terra-clinical-application',
  testSetup,
});

// custom / manual test specs
describe('NoOverflowColumnDataGrid', () => {
    describe('No Overflow Column Data Grid', ()=> {
        before(() => browser.url('...'));
        
        describe('with veritical overflow', () => {
            beforeEach(() => browser.click('[data-cell-label="section_0-29-Column-0"]'));

            Terra.should.matchScreenshot({ selector: '#no-overflow-column-data-grid' });
            Terra.should.beAccessible();
        });
    });
});
```

**Comment by ryanthemanuel** [comment]
I do want to start simpler, I was just trying to play around and see if I could get all testing into this manner.  I agree with the config you suggested, but am curious what other opinions are as well.

I originally had the config passed into the `wdioTestDevSiteSnapshots` function, but I waffled and moved it to be located in the same place as the files they were associated with.  I see that as a convenience, but I agree with your points.  Curious about other feedback for this as well.

**Comment by ryanthemanuel** [comment]
I also think we could extend this to a jest test version as well.  For open source I think we'll have a decent amount of benefits, but our pattern of Application -> Container -> View gets wonky because the dev site examples are typically at the Application level and we'd want to jest test at each View level.

**Comment by ryanthemanuel** [comment]
Curious what people might think also rather than taking out actions completely, adding a "setup" to allow consumers to pass in things like "click" to set things up.
