### ISSUE TITLE
Custom index template support

### ISSUE THREAD

**Issue by nickpith** [cerner/terra-dev-site#125]
# Feature Request

## Description
When using terra-dev-site, we have some external scripts that are not included as part of our Webpack config that we would like loaded on our dev site. When talking with @bjankord, he thought it would be a good idea to allow custom templates to be specified with the terra-dev-site config so that we can do whatever we want.

## Additional Context / Screenshots
* https://github.com/cerner/terra-dev-site/blob/master/config/webpack/terra-dev-site.webpack.config.js#L86

**Comment by bjankord** [comment]
We could open this config option to pull a config item from site config, allowing users to specify their own html file.

**Comment by mjhenkes** [comment]
Have you looked at using side effect imports to load the external scripts? It will add them to the webpack bundle, which might not be desired.
https://github.com/cerner/terra-dev-site/blob/master/config/site/site.config.js#L67

I think it would be pretty straight forward to allow consumers to supply their own template html file if needed. We'd have to document how to write the template because some features of dev site (translations) could break if there are missing fields.

Here is where we specify which html file to use: 
https://github.com/cerner/terra-dev-site/blob/master/config/webpack/terra-dev-site.webpack.config.js#L86

Here is the current template. 
https://github.com/cerner/terra-dev-site/blob/master/src/index.html

Specifically Title, language and direction would have to be filled out as well as having 100% height set and a div with the root id.

We should also make sure site works without language and direction specified in the template if we open it up.

**Comment by nickpith** [comment]
In this particular case, the scripts are hosted on a CDN for things like polyfills and loading an SDK.

**Comment by nickpith** [comment]
I don't believe the sideEffectImports will work for that use case.

**Comment by emilyrohrbough** [comment]
@mjhenkes I'm not sure we can drop the directionality specified on the index template. Terra's component styles are dependent on which direction is specified.

**Comment by mjhenkes** [comment]
@emilyrohrbough we can't drop it but we can default it to 'ltr' if it's not found on the html document

https://github.com/cerner/terra-dev-site/blob/master/src/app/App.jsx#L87

**Comment by emilyrohrbough** [comment]
That is true!

**Comment by alex-bezek** [comment]
Rather than making the user create their own index.html file, can we instead rely on the fact that the webpack config is using HtmlWebpackPlugin which supports templates in the html such as ejs?

I hacked together a solution locally on my project. Since there isn't a clean way currently to choose my own index file (per above discussions) i modified my webpack config to supply my own HtmlWebpackPlugin config and point to an index.html file of my own.

I changed it to
```html
<!doctype html>
<html lang="<%= htmlWebpackPlugin.options.lang %>" dir="<%= htmlWebpackPlugin.options.dir %>">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= htmlWebpackPlugin.options.newRelicJS %>
    <title><%= htmlWebpackPlugin.options.title %></title>
    <% try { %>
      <%= require('html-loader!./preview-head.html') %>
    <% }catch(e) { %>
      <% console.log("No preview html found. Skipping") %>
    <% } %>
  </head>
  <body style="height: 100%;">
    <div id="root"></div>
  </body>
</html>
```
and provided a preview-head.html file at my root directoy that has
```html
<script src="https://d3rc9bvtvjyh73.cloudfront.net/healthelife-sdk/healthelife_sdk.js"></script>
```
Running this produces the script tag in my head as expected.
![image](https://user-images.githubusercontent.com/8029578/54731338-b73f5900-4b5b-11e9-9ccc-b16e58b6d48a.png)

Removing the preview-head.html file still compiles and just produces this log warning
![image](https://user-images.githubusercontent.com/8029578/54731374-ece44200-4b5b-11e9-9555-55f233851167.png)

Let me know if you see any issues with this approach

**Comment by alex-bezek** [comment]
I did try this out on the repo, but i'm having an issue loading the file. I went as far as hardcoding the html-loader path directly to an html file like 
```
    <% try { %>
      <% console.log("debug info") %>
      <% console.log(process.cwd()) %>
      <% console.log(__dirname) %>
      <%= require('html-loader!/Users/as027811/code/work/terra-dev-site/lib/preview-head.html') %>
    <% }catch(e) { %>
      <% console.log(e) %>
      <% console.log("No preview html found. Skipping") %>
    <% } %>
```
but I still get
```
Terra-Toolkit 4.22.0 started
* Local:            http://0.0.0.0:8080/
* On your network:  http://192.168.0.203:8080/

debug info
/
/
{ Error: Cannot find module 'html-loader!/Users/as027811/code/work/terra-dev-site/lib/preview-head.html'
    at webpackMissingModule (/Users/as027811/code/work/terra-dev-site/lib/index.html:117:75)
    at /Users/as027811/code/work/terra-dev-site/lib/index.html:117:224
    at ./node_modules/html-webpack-plugin/lib/loader.js!./lib/index.html.module.exports (/Users/as027811/code/work/terra-dev-site/lib/index.html:128:3)
    at Promise.resolve.then (/Users/as027811/code/work/terra-dev-site/node_modules/html-webpack-plugin/index.js:284:18)
    at <anonymous> code: 'MODULE_NOT_FOUND' }
No preview html found. Skipping
```
even though the path is correct.
```
cat /Users/as027811/code/work/terra-dev-site/lib/preview-head.html                                                                  as027811@M1711984  06:02   100% 
<script src="https://a-cool-script.js"></script>%
```
If someone that knows a bit more about loaders knows whats up, let me know. If the absolute path can work, you could either assume the preview-head.html is at the root folder, or you could expose a config the consumer passes in perhaps

**Comment by mjhenkes** [comment]
@alex-bezek, I like where you're going with this. I've been playing with something similar for other reasons. Have you taken a look at how the new relic js is getting included? I think it's doing what you are looking for. Though I think we should think through a better more general strategy that allows for:
1.  any number of Arbitrary js files
2. Additional webpack entrypoints
3. ordering
4. appending to either head or body.

**Comment by alex-bezek** [comment]
I have now :)
I got the preview-head.html concept from storybook. Their approach is tto just look for a set of hardcoded html file names in the consumer's system.
https://github.com/storybooks/storybook/blob/4da246bbe9413510b48d1ab8b9faf4fae4656d92/lib/core/src/server/utils/template.js#L16 . I guess you would just want to weigh how config heavy you want to be vs relying on conventions
