### ISSUE TITLE
"Cannot read property 'target' of undefined" in the search filter

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-dev-site#172]
# Bug Report
The search filter occasionally has null event target.  Not sure what would cause that:

https://rpm.newrelic.com/accounts/1721539/browser/142450088/errors/details#?tw_start=&tw_end=now&tw_offset=43200000&selectedItem=Cannot%20read%20property%20'target'%20of%20undefined&selectedTab=instances

![image](https://user-images.githubusercontent.com/4873279/59777317-12c3d480-927a-11e9-8f0d-bfec18dadeb1.png)

**Comment by bjankord** [comment]
Do we know what browser this is happening in?

**Comment by dkasper-was-taken** [comment]
Looks to happen in Chrome. The handleFilter message is passed to the SearchField:
https://github.com/cerner/terra-dev-site/blob/master/src/app/components/DevSiteRoutingMenu.jsx#L178

The in the onKeyDown on the SearchField, when the ESC key is pressed, we call handleClear with no event:
https://github.com/cerner/terra-core/blob/master/packages/terra-search-field/src/SearchField.jsx#L176

Which then calls the onChange with that empty event:
https://github.com/cerner/terra-core/blob/master/packages/terra-search-field/src/SearchField.jsx#L176

**Comment by nramamurth** [comment]
1. I think this could be fixed in `terra-dev-site` by making use of the second argument of the `onChange` callback so that it clears the search field without error-ing out upon ESC key press or the clear button click. Using `event.target.value` forces `handleFilter` to behave differently otherwise for ESC key press and clear button click.

```diff
- handleFilter(event) {
+ handleFilter(event, filterText) {
-   const filterText = event.target.value;
    const { menuItems: initialMenuItems } = this.props;

    const filter = searchFilter(filterText);
    const menuItems = initialMenuItems.filter(({ text }) => filter(text));

    this.setState({ menuItems });
}
```

2. Having said that, like @dkasper-was-taken pointed out, the `handleClear` call [1] nevertheless needs to send down the `event` object so that this issue does not occur for other consumers. 

@ryanthemanuel Could we log a separate issue in `terra-core` to fix the `SearchField` in addition to this issue in `terra-dev-site`?

**Comment by ryanthemanuel** [comment]
@nramamurth that sounds good.  Feel free to log it.
