### ISSUE TITLE
Create Webpack Loader "Src Code Badge"

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-dev-site#235]
# Feature Request

## Description
In our docs, we add text like:
```md
[View component source code](https://github.com/cerner/terra-framework/tree/master/packages/terra-application-layout)
```
It would be nice if this information was available via a badge like the component version. This would pull the url provided in the package.json. This would require updates to our package.jsons for each component, but I think it's a better change anyways so component code is correctly linked on NPM.

**Comment by ShettyAkarsh** [comment]
@emilyrohrbough , so we use this [Badge](https://github.com/cerner/terra-dev-site/blob/71207048039042be130ab51007953e53bd4fa106/src/loader-components/_NpmBadge.jsx#L23-L34)  provided by terra-dev-site across all the components in our dev-site.  which will display in the following format 
![image](https://user-images.githubusercontent.com/45097016/75547855-e17ae580-5a51-11ea-9c19-ee715550d078.png)

so here with this change are you expecting the format to be **Source Code** as the text and latest version of the component ? so that clicking on that should open git source code page ?
