### ISSUE TITLE
Add ability to search on dev site

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-dev-site#93]
# Feature Request

## Description
Add ability to search through dev site. It would be helpful for consumers if they had an easy way to search and find information on the dev site.

## Additional Context / Screenshots
I'd recommend taking a look at https://www.algolia.com/ 
They power the search on https://material-ui.com/ and a couple other react UI sites.
This could likely be implemented the same way we do New Relic config.

**Comment by CoryMcDonald** [comment]
I've contacted Algolia about this and they responded 
>Hi Cory,
>Thank you for your interest in Algolia DocSearch! We would love to help your project with the search but we'll need to inject a small JavaScript snippet in the page: are you able to do that? Are you a maintainer of the website?
>Let us know!
>Tim Carry

Emailed them back and I'll submit a PR once I have the snippet

**Comment by CoryMcDonald** [comment]
The site does have to be publicly accessible because they essentially crawl the documentation site. This is a free service provided to libraries, and it seems fairly hands on from their side. Essentially it's like a google custom domain search but better.

For internal documentation we would have to upload our data to their servers so that they would be able to query and search it using their algorithms. 

As for the javascript key to identify the application, i'm not quite sure. There's some work that i'm doing to allow for better SEO and discoverability so their crawler will work

**Comment by JakeLaCombe** [comment]
I wonder if GraphQL is a possibility here. http://graphql.github.io/

It's queries off an existing dataset, which we could use on the site configuration file potentially.

**Comment by CoryMcDonald** [comment]
It certainly is an option, but all the components are on one page. You could just control + F to find them. What Algolia provides page title documentation, and content searching. In addition it seems like all great open source projects use it - React, Bootstrap, Vue, Babel, Flow, Gitlab, Moment.js, etc.

**Comment by mjhenkes** [comment]
resolved with v6
